config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "notes#timed"

  resources :notes
  get 'notes/new', to: 'notes#new'
  get '/timed', to: 'notes#timed'

  resources :labels

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :user
  has_many :notes, dependent: :destroy
  validates :title, presence: true, length: { maximum: 20 }
  validates_uniqueness_of :title, scope: :user
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :label
  validates :head, presence: true, length: { maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes, dependent: :destroy
  has_many :labels, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_label, only: %i[ show edit update destroy ] # set_label makes new, edit, and update empty

  # GET /labels or /labels.json
  def index
    # @labels = Label.all
    @labels = current_user.labels.all
  end

  # GET /labels/1 or /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels or /labels.json
  def create
    @label = Label.new(label_params)
    @label.user = current_user

    respond_to do |format|
      if @label.save
        format.html { redirect_to label_url(@label), notice: "Label was successfully created." }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1 or /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to label_url(@label), notice: "Label was successfully updated." }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1 or /labels/1.json
  def destroy
    @label.destroy

    respond_to do |format|
      format.html { redirect_to labels_url, notice: "Label was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = current_user.labels.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def label_params
      params.require(:label).permit(:title)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: %i[ show edit update destroy] # set_note makes new, edit, and update empty
  before_action :set_label

  # GET /notes or /notes.json
  def index
    # @notes = Note.all
    @notes = current_user.notes.all
  end

  # GET /notes or /notes.json with deadlines
  def timed
    @notes_timed = []
    @notes = current_user.notes.all.reverse_each
    @notes.each do |note|
        if note.deadline && note.deadline.today?
            @notes_timed.push(note)
        end
    end
    @notes_timed
  end

  # GET /notes/1 or /notes/1.json
  def show
    # @note = Note.find(params[:id])
    @note = current_user.notes.find(params[:id])
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
    @current_label = @note.label
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)
    @note.user = current_user

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = current_user.notes.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:head, :body, :deadline, :label_id)
    end

    # Define labels to be displayed for label setting of notes.
    def set_label
      @labels = current_user.labels.all.order(:title)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow sticky-top">
  <div class="container-fluid">
    <div class="navbar-brand">
      <h3 class="">MU's Notes App</h3>
    </div>
    <button class="navbar-toggler rotating" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <ul class="nav nav-pills me-auto mb-2 mb-lg-0 w-100 justify-content-end align-items-center px-5">
          <li class="nav-item m-2">
            <%= link_to "Today's Notes", timed_path, class: "nav-link"%>
          </li>
          <li class="nav-item m-2">
            <%= link_to 'All Notes', notes_path, class: "nav-link"%>
          </li>
          <li class="nav-item m-2">
            <%= link_to 'All Labels', labels_path, class: "nav-link"%>
          </li>
        </ul>
        <div class="d-flex align-items-center justify-content-center text-decoration-none">
          <div class="btn btn-sm dropdown text-decoration-none p-0">
            <a class="btn dropdown-toggle text-primary text-decoration-none" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <span class="text-decoration-none"><%= current_user.email %></span>
            </a>
            <ul class="dropdown-menu nav-pills" aria-labelledby="navbarDropdown">
              <li class="nav-item m-2">
                <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link active text-success bg-light m-1 mb-4"%>
              </li>
              <li class="nav-item m-2">
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link active text-danger bg-light m-1 mb-2"%>
              </li>
            </ul>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/application/_header2.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow sticky-top">
  <div class="container-fluid">
    <%= link_to "THE APP", timed_path, class: "navbar-brand btn"%>
    <% if user_signed_in? %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item m-2">
            <%= link_to "Today's Notes", timed_path, class: "nav-link btn btn-outline-primary border-0 text-dark"%>
          </li>
          <li class="nav-item m-2">
            <%= link_to 'All Notes', notes_path, class: "nav-link btn btn-outline-primary border-0 text-dark"%>
          </li>
          <li class="nav-item m-2">
            <%= link_to 'All Labels', labels_path, class: "nav-link btn btn-outline-primary border-0 text-dark"%>
          </li>
        </ul>
        <div class="btn btn-sm dropdown text-decoration-none p-0">
          <a class="btn dropdown-toggle text-primary text-decoration-none" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="text-decoration-none"><%= current_user.email %></span>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li class="nav-item m-2">
              <%= link_to 'My Account', edit_user_registration_path, class: "nav-link active text-success bg-light m-1 mb-4"%>
            </li>
            <li class="nav-item m-2">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link active text-danger bg-light m-1 mb-2"%>
            </li>
          </ul>
        </div>
      <%end%>
    </div>
  </nav>

app/views/application/_new-items.html.erb
<% if user_signed_in? %>
<!-- Button trigger modal -->
<div class="fixed-bottom w-100 d-flex justify-content-end p-5">
  <button type="button" class="btn btn-success btn-lg shadow" data-bs-toggle="modal" data-bs-target="#newButton">
    NEW
  </button>
</div>
<!-- Modal -->
<div class="modal fade" id="newButton" tabindex="-1" aria-labelledby="newButtonLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered w-100" style="width: 25rem;">
    <div class="modal-content d-flex flex-column align-items-center bg-transparent border-0">
      <button type="button" class="my-3 btn-outline-warning btn-lg border-0 bg-transparent rounded-circle m-4" data-bs-dismiss="modal" aria-label="Close">❌</button>
      <%= link_to 'New Note', new_note_path, class: "btn btn-light btn-lg btn-block m-4 text-dark" %>
      <%= link_to 'New Label', new_label_path, class: "btn btn-dark btn-lg btn-block m-4 text-light" %>
    </div>
  </div>
</div>
<%end%>

app/views/labels/_form.html.erb
<%= form_with(model: label) do |form| %>
  <div class="d-flex flex-column flex-wrap justify-content-center align-items-center pt-3 mt-1 off-white">
    <div class="d-flex flex-row flex-wrap justify-content-center pt-1 mt-1 off-white">
      <div class="card m-2 shadow d-flex flex-column justify-content-between align-items-center bg-light border-0" style="width: 25rem;">
        <div class="field w-75 m-2 mt-4">
          <%= form.text_field :title, placeholder: "Maximum of 20 characters only", class: "text-center form-control" %>
        </div>
        <div class="field">
          <%= form.number_field :user_id, id: :note_user_id, value: current_user.id, type: :hidden %>
        </div>
        <div class= "actions mb-3">
          <%= form.submit %>
        </div>
      </div>
    </div>
  </div>
  <% if label.errors.any? %>
    <div class="d-flex flex-wrap justify-content-center mt-2">
      <% label.errors.full_messages.each do |message| %>
        <div class="alert alert-danger m-2" role="alert"><%= message %></div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/labels/edit.html.erb
<h2 class=" px-3 text-center pt-2 mt-2">Edit Label</h2>

<%= render 'form', label: @label %>

app/views/labels/index.html.erb
<h2 class=" px-3  text-center pt-2 mt-2">All Labels</h2>
<div class="d-flex flex-row flex-wrap justify-content-center pt-1 mt-1 off-white">
  <% @labels.each do |label| %>
    <div class="bg-dark border-0 card m-4 shadow d-flex flex-column justify-content-between" style="width: 18rem; height: auto;">
      <%= link_to label_path(label), class: "btn" do %>
        <div class="card-body d-flex flex-column align-items-center">
          <h4 class="card-head pb-1 text-light text-left"><%= label.title.truncate(15) %></h4>
          <p class="card-text text-light mx-1 text-left"> <%= label.notes.empty? ? 'No associated Note/s' : 'Click to see associated Note/s'%> </p>
        </div>
      <% end %>
      <div class="d-flex flex-row justify-content-center align-items-center m-2">
        <%= link_to 'Edit', edit_label_path(label), class: "btn btn-success btn-sm p-1 m-1 rounded border-0 font-weight-bold text-light" %>
        <%= link_to 'Delete', label_path(label), method: :delete, data: {confirm: 'Delete chosen label and associated notes PERMANENTLY?'}, class: "btn btn-danger btn-sm p-1 m-1 rounded border-0 font-weight-bold text-light" %>
      </div>
    </div>
  <% end %>
</div>

app/views/labels/new.html.erb
<h2 class=" px-3  text-center pt-2 mt-2">New Label</h2>

<%= render 'form', label: @label %>

app/views/labels/show.html.erb
<h2 class=" px-3  text-center pt-2 mt-2"><%= @label.title%></h2>
<div class="d-flex flex-row justify-content-center align-items-center m-2">
  <%= link_to 'Edit', edit_label_path(@label), class: "btn btn-success btn-sm p-1 m-1 rounded border-0 font-weight-bold text-light" %>
  <%= link_to 'Delete', label_path(@label), method: :delete, data: {confirm: 'Delete chosen label and associated notes PERMANENTLY?'}, class: "btn btn-danger btn-sm p-1 m-1 rounded border-0 font-weight-bold text-light" %>
</div>
<h4 class="text-center"> <%= @label.notes.empty? ? 'No associated Note/s' : ''%> </h4>
<div class="d-flex flex-row flex-wrap justify-content-center pt-1 mt-1 off-white">
  <% @label.notes.each do |note| %>
    <div class="bg-light border-0 card m-4 shadow d-flex flex-column justify-content-between" style="width: 18rem; height: auto;">
      <%= link_to note_path(note), class: "btn" do %>
        <div class="card-body d-flex flex-column align-items-center">
          <h4 class="card-head pb-1 text-dark text-left"><%= note.head.truncate(15) %></h4>
          <p class="card-text text-muted mx-1 text-left"><%= note.body.empty? ? 'No Details' : 'Click to see Details' %></p>
          <div class="d-flex flex-row flex-wrap justify-content-start align-items-center">
            <button class="btn btn-info btn-sm p-1 m-1 rounded border-0 font-weight-bold"> <%= note.deadline ? note.deadline.strftime('%d %b %Y %I:%M %p') : 'No Deadline' %> </button>
          </div>
        </div>
      <% end %>
      <div class="d-flex flex-row justify-content-center align-items-center m-2">
        <%= link_to 'Edit', edit_note_path(note), class: "btn btn-success btn-sm p-1 m-1 rounded border-0 font-weight-bold text-light" %>
        <%= link_to 'Delete', note_path(note), method: :delete, data: {confirm: 'Delete chosen note PERMANENTLY?'}, class: "btn btn-danger btn-sm p-1 m-1 rounded border-0 font-weight-bold text-light" %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="container-fluid trix-content change-font align-items-center">
    <%= render "header2" %>
    <%= yield %>
    <%= render "new-items" %>
    <div class="d-flex flex-wrap justify-content-center fixed-bottom m-5">
      <% if notice %>
        <div class="alert alert-success text-center m-3"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger text-center m-3"><%= alert %></div>
      <% end %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <div class="d-flex flex-column flex-wrap justify-content-center align-items-center pt-3 mt-1 off-white">
    <div class="d-flex flex-row flex-wrap justify-content-center pt-1 mt-1 off-white">
      <div class="card m-2 shadow d-flex flex-column justify-content-between align-items-center bg-light border-0" style="width: 25rem;">
        <div class="field w-75 m-2 mt-4">
          <%= form.text_field :head, placeholder: "Maximum of 30 characters only", class: "text-center form-control"%>
        </div>
        <div class="field w-75 m-2">
          <%= form.text_area :body, placeholder: "Optional additional information here", class: "text-center form-control w-100"%>
        </div>
        <div class="field m-2 text-center">
          <%= form.label 'Deadline (Optional)', class: "card-text text-dark mb-2" %>
          <%= form.datetime_local_field :deadline, min: Date.today, class: "form-control" %>
        </div>
        <div class="field m-2 text-center">
          <%= form.label 'Label (Required)', class: "card-text text-dark" %>
          <%= form.select :label_id, options_for_select(@labels.collect { |label| [label.title, label.id]}), :include_blank => true %>
          <p class="card-text text-danger mt-2"> <%= @current_label ? 'Previous label was ' + @current_label.title : '' %>  </p>
        </div>
        <div class="field">
          <%= form.number_field :user_id, id: :note_user_id, value: current_user.id, type: :hidden %>
        </div>
        <div class= "actions mb-3">
          <%= form.submit %>
        </div>
      </div>
    </div>
  </div>
  <% if note.errors.any? %>
    <div class="d-flex flex-wrap justify-content-center mt-2">
      <% note.errors.full_messages.each do |message| %>
        <div class="alert alert-danger m-2" role="alert"><%= message %></div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/notes/edit.html.erb
<h2 class=" px-3  text-center pt-2 mt-2">Editing Note</h2>
<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<h2 class=" px-3  text-center pt-2 mt-2"><%= @notes.empty? ? 'No Notes' : "All Notes"%></h2>
<div class="d-flex flex-row flex-wrap justify-content-center pt-1 mt-1 off-white">
  <% @notes.each do |note| %>
    <div class="bg-light border-0 card m-4 shadow d-flex flex-column justify-content-between" style="width: 18rem; height: auto;">
      <%= link_to note_path(note), class: "btn" do %>
        <div class="card-body d-flex flex-column align-items-center">
          <h4 class="card-head pb-1 text-dark text-left"><%= note.head.truncate(15) %></h4>
          <p class="card-text text-muted mx-1 text-left"><%= note.body.empty? ? 'No Details' : 'Click to see Details' %></p>
          <div class="d-flex flex-row flex-wrap justify-content-start align-items-center">
            <button class="btn btn-info btn-sm p-1 m-1 rounded border-0 font-weight-bold"> <%= note.deadline ? note.deadline.strftime('%d %b %Y %I:%M %p') : 'No Deadline' %> </button>
          </div>
        </div>
      <% end %>
      <div class="d-flex flex-row justify-content-between align-items-center m-2">
        <%= link_to label_path(note.label), class: "btn btn-dark btn-sm p-1 m-1 rounded border-0 font-weight-bold text-light" do %>
          <%= note.label.title.truncate(10) %>
        <%end%>
        <div class="d-flex flex-row justify-content-end align-items-center m-2">
          <%= link_to 'Edit', edit_note_path(note), class: "btn btn-success btn-sm p-1 m-1 rounded border-0 font-weight-bold text-light" %>
          <%= link_to 'Delete', note_path(note), method: :delete, data: {confirm: 'Delete chosen note PERMANENTLY?'}, class: "btn btn-danger btn-sm p-1 m-1 rounded border-0 font-weight-bold text-light" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/notes/new.html.erb
<h2 class=" px-3  text-center pt-2 mt-2">New Note</h2>
<%= render 'form', note: @note %>

app/views/notes/show.html.erb
<h2 class=" px-3  text-center pt-2 mt-2"><%= @note.head%></h2>
<div class="d-flex flex-column flex-wrap justify-content-center align-items-center pt-3 mt-1 off-white">
  <div class="d-flex flex-row flex-wrap justify-content-center pt-1 mt-1 off-white">
      <div class="bg-light border-0 card m-4 shadow d-flex flex-column justify-content-between" style="min-width: 18rem; height: auto;">
          <div class="card-body d-flex flex-column align-items-center">
            <p class="card-text text-dark mx-1 text-left"><%= @note.body.empty? ? 'No Details' : @note.body %></p>
            
            <div class="d-flex flex-row flex-wrap justify-content-start align-items-center">
              <button class="btn btn-info btn-sm p-1 m-1 rounded border-0 font-weight-bold"> <%= @note.deadline ? @note.deadline.strftime('%d %b %Y %I:%M %p') : 'No Deadline' %> </button>
            </div>
          </div>
        <div class="d-flex flex-row justify-content-between align-items-center m-2">
          <%= link_to label_path(@note.label), class: "btn btn-dark btn-sm p-1 m-1 rounded border-0 font-weight-bold text-light" do %>
            <%= @note.label.title.truncate(10) %>
          <%end%>
          <div class="d-flex flex-row justify-content-end align-items-center m-2">
            <%= link_to 'Edit', edit_note_path(@note), class: "btn btn-success btn-sm p-1 m-1 rounded border-0 font-weight-bold text-light" %>
            <%= link_to 'Delete', note_path(@note), method: :delete, data: {confirm: 'Delete chosen note PERMANENTLY?'}, class: "btn btn-danger btn-sm p-1 m-1 rounded border-0 font-weight-bold text-light" %>
          </div>
        </div>
    </div>
  </div>

app/views/notes/timed.html.erb
<h2 class=" px-3  text-center pt-2 mt-2"><%= @notes_timed.empty? ? 'No Notes for Today' : "Today's Notes"%></h2>
<div class="d-flex flex-row flex-wrap justify-content-center pt-1 mt-1 off-white">
  <% @notes_timed.each do |note| %>
    <div class="bg-light border-0 card m-4 shadow d-flex flex-column justify-content-between" style="width: 18rem; height: auto;">
      <%= link_to note_path(note), class: "btn" do %>
        <div class="card-body d-flex flex-column align-items-center">
          <h4 class="card-head pb-1 text-dark text-left"><%= note.head.truncate(15) %></h4>
          <p class="card-text text-muted mx-1 text-left"><%= note.body.empty? ? 'No Details' : 'Click to see Details' %></p>
          <div class="d-flex flex-row flex-wrap justify-content-start align-items-center">
            <button class="btn btn-info btn-sm p-1 m-1 rounded border-0 font-weight-bold"> <%= note.deadline ? note.deadline.strftime('%I:%M %p') : 'No Deadline' %> </button>
          </div>
        </div>
      <% end %>
      <div class="d-flex flex-row justify-content-between align-items-center m-2">
        <%= link_to label_path(note.label), class: "btn btn-dark btn-sm p-1 m-1 rounded border-0 font-weight-bold text-light" do %>
          <%= note.label.title.truncate(10) %>
        <%end%>
        <div class="d-flex flex-row justify-content-end align-items-center m-2">
          <%= link_to 'Edit', edit_note_path(note), class: "btn btn-success btn-sm p-1 m-1 rounded border-0 font-weight-bold text-light" %>
          <%= link_to 'Delete', note_path(note), method: :delete, data: {confirm: 'Delete chosen note PERMANENTLY?'}, class: "btn btn-danger btn-sm p-1 m-1 rounded border-0 font-weight-bold text-light" %>
        </div>
      </div>
    </div>
  <% end %>
</div>